export const requestTypes ={

    SET_INITIAL_AUTH_STATE : "SET_INITIAL_AUTH_STATE",
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_LOGOUT:  'LOGIN_LOGOUT',

    MERCHANTS_REQUEST: 'MERCHANTS_REQUEST',
    MERCHANTS_SUCCESS: 'MERCHANTS_SUCCESS', 
    MERCHANTS_SELECT: 'MERCHANTS_SELECT',

    APIPERFIL_REQUEST:'APIPERFIL_REQUEST',
    APIPERFIL_SUCCESS: 'APIMERCHANT_SUCCESS',
    APIPERFIL_FAILURE: 'APIPERFIL_FAILURE',

    FETCH_ADDRESS_REQUEST: 'FETCH_ADDRESS_REQUEST',
    FETCH_ADDRESS_SUCCESS: 'FETCH_ADDRESS_SUCCESS',
    FETCH_ADDRESS_FAILURE: 'FETCH_ADDRESS_FAILURE',
   

    UPDATE_FORM_FIELD: 'UPDATE_FORM_FIELD:',
    RESET_FORM:'RESET_FORM',
    SUBMIT_ADDRESS_REQUEST:'SUBMIT_ADDRESS_REQUEST',
    SUBMIT_ADDRESS_SUCCESS: 'SUBMIT_ADDRESS_SUCCESS',
    SUBMIT_ADDRESS_FAILURE: 'SUBMIT_ADDRESS_FAILURE',

    // Profile Types 
    FETCH_PROFILE_REQUEST: 'FETCH_PROFILE_REQUEST',
    FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
    FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE',

   // UPDATE_FORM_FIELD: 'UPDATE_FORM_FIELD:',
    RESET_FORM:'RESET_FORM',
    SUBMIT_PROFILE_REQUEST:'SUBMIT_PROFILE_REQUEST',
    SUBMIT_PROFILE_SUCCESS: 'SUBMIT_PROFILE_SUCCESS',
    SUBMIT_PROFILE_FAILURE: 'SUBMIT_PROFILE_FAILURE',
    UPDATE_FORM_FIELD: ' UPDATE_FORM_FIELD' ,
    
    UPDATE_IMAGE_FIELD: 'UPDATE_IMAGE_FIELD',

    APIMENU_REQUEST:'APIMENU_REQUEST',
    APIMENU_SUCCESS: 'APIMENU_SUCCESS',
    APIMENU_FAILURE: 'APIMENU_FAILURE',
    

    APICATEGORY_REQUEST: 'APICATEGORY_REQUEST',
    APICATEGORY_SUCCESS: 'APICATEGORY_SUCCESS',
    APICATEGORY_FAILURE: 'APICATEGORY_FAILURE',

    SUBMIT_CATEGORY_REQUEST:'SUBMIT_CATEGORY_REQUEST',
    SUBMIT_CATEGORY_SUCCESS: 'SUBMIT_CATEGORY_SUCCESS',
    SUBMIT_CATEGORY_FAILURE: 'SUBMIT_CATEGORY_FAILURE',

    APICATEGORYBYID_REQUEST: 'APICATEGORYBYID_REQUEST',
    APICATEGORYBYID_SUCCESS: 'APICATEGORYBYID_SUCCESS',
    APICATEGORYBYID_FAILURE: 'APICATEGORYBYID_FAILURE',

    APIITEM_REQUEST: 'APIITEM_REQUEST',
    APIITEM_SUCCESS:  'APIITEM_SUCCESS',
    APIITEM_FAILURE:  'APIITEM_FAILURE',
    APIITEM_STATUS: 'APIITEM_STATUS',
    APIPIZZA_STATUS: 'APIPIZZA_STATUS',
    SELECT_CATALOG : 'SELECT_CATALOG', 
    DESELECT_CATALOG : 'DESELECT_CATALOG', 
    CLEAR_SELECTED_CATALOGS : 'CLEAR_SELECTED_CATALOGS',

    APIPRODUCT_REQUEST: 'APIPRODUCT_REQUEST',
    APIPRODUCT_SUCCESS: 'APIPRODUCT_SUCCESS',
    APIPRODUCT_FAILED: 'APIPRODUCT_FAILED',
}